{{- if .Values.secrets.keyValues }}
{{- range $i, $value := .Values.secrets.keyValues }}
---  
apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data: 
  {{- range $key, $val := $value.data }}
  {{ print $key }}: {{ print $val | b64enc -}}  
  {{ end -}}
{{ end -}}
{{- end }}

{{- if .Values.externalSecretsEnabled }}
{{- range $i, $value := .Values.externalSecrets.keyValues }}
---  
apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data: 
  {{- range $key, $val := $value.data }}
  {{ print $key }}: {{ print $val | b64enc -}}  
  {{ end -}}
{{ end -}}
{{- end }}